/**
 *  Valores por defecto del formulario
 */
export const FORM_INIT_CONCEPTO = { 
    /** Basico */
        prieje: 0, 
        functo: '1', 
        mansal: '0', 
        graimp: '0', 
        noimpr: false, 
        noneto: false, 
        incdet: false, 
        abopre: false, 
        montocero: false, 
        topmon: false,
        facafe: 0,
        inactivo: false, 
    /** Salario */
        tipsue: '0',
        salmin: 0,
        sussue: '0',
        salmis: 0,
        topsue: false,
    /** Valor */
        valcto: 0,
        sueval: '0',
        suecav: false,
        bussuv: false,
        salmiv: false,
        serval: '0',
        valmes: false,
        topval: false,
    /** Factor */
        faccto: 0,
        suefac: '0',
        suecaf: false,
        bussuf: false,
        salmif: false,
        serfac: '0',
        facmes: false,
        faccen: false,
        topfac: false,
    /** Cantidad */
        cancto: 0,
        suecan: '0',
        suecac: false,
        bussuc: false,
        salmic: false,
        sercan: '0',
        facimp: 0,
        candia: 0,
        canmes: false,
        topcan: false,
    /** LIMITE */
        conlim: '0',
        canlid: 0,
        canlih: 0,
        liminf: 0,
        limsup: 0,
        limsue: '0',
        suelim: false,
        salmil: false,
    /** PROCESAR */
        autpro: '2',
        profij: false,
        fijing: false,
        prope1: false,
        prope2: false,
        prope3: false,
        prope4: false,
        prope5: false,
        proani: false,
        conexc: false,
    /** Vacación */
        afereg: false,
        conabo: false,
        posvac: false,
        calabo: '0',
        concuo: '0',
    /** Miscelanea */
        facfij: 0,
        suscuota: false,
        manins: false,
        facaho: 0,
        unasup: false,
    /** Otros */
        capint: '0',
        cretro: '0',
        acuche: '0',
        gretro: '0'
};
