// Grupo Rotacion
export interface GrupoRotacion {
    idEmpresa:   string;
    idNomina:    string;
    idGrupo:     string;
    congru:      string;
    diag01?:     string | null;
    diag02?:     string | null;
    diag03?:     string | null;
    diag04?:     string | null;
    diag05?:     string | null;
    diag06?:     string | null;
    diag07?:     string | null;
    diag08?:     string | null;
    diag09?:     string | null;
    diag10?:     string | null;
    diag11?:     string | null;
    diag12?:     string | null;
    diag13?:     string | null;
    diag14?:     string | null;
    diag15?:     string | null;
    diag16?:     string | null;
    diag17?:     string | null;
    diag18?:     string | null;
    diag19?:     string | null;
    diag20?:     string | null;
    diag21?:     string | null;
    diag22?:     string | null;
    diag23?:     string | null;
    diag24?:     string | null;
    diag25?:     string | null;
    diag26?:     string | null;
    diag27?:     string | null;
    diag28?:     string | null;
    diag29?:     string | null;
    diag30?:     string | null;
    diag31?:     any;
    diav01?:     any;
    diav02?:     any;
    diav03?:     any;
    diav04?:     any;
    diav05?:     any;
    diav06?:     any;
    diav07?:     any;
    diav08?:     any;
    diav09?:     any;
    diav10?:     any;
    diav11?:     any;
    diav12?:     any;
    diav13?:     any;
    diav14?:     any;
    diav15?:     any;
    diav16?:     any;
    diav17?:     any;
    diav18?:     any;
    diav19?:     any;
    diav20?:     any;
    diav21?:     any;
    diav22?:     any;
    diav23?:     any;
    diav24?:     any;
    diav25?:     any;
    diav26?:     any;
    diav27?:     any;
    diav28?:     any;
    diav29?:     any;
    diav30?:     any;
    diav31?:     any;
    canlim?:     number;
    diaga1?:     any;
    diaga2?:     any;
    diaga3?:     any;
    diaga4?:     any;
    diava1?:     any;
    diava2?:     any;
    diava3?:     any;
    diava4?:     any;

    // Colocar un id temporal en el registro para el [dataKey] de la tabla
    idTableTemporal: number
}